sequenceDiagram
  participant participant_ChessBoard as ChessBoard
  participant participant_useZoraTheme as useZoraTheme
  participant_ChessBoard->>participant_useZoraTheme: useZoraTheme()
  participant_useZoraTheme-->>participant_ChessBoard: return
