sequenceDiagram
  participant participant_OpeningBook as OpeningBook
  participant participant_useZoraTheme as useZoraTheme
  participant_OpeningBook->>participant_useZoraTheme: useZoraTheme()
  participant_useZoraTheme-->>participant_OpeningBook: return
