graph TD
  package__ankhorage_zora_chessboard["@ankhorage/zora-chessboard"]
  entrypoint_src_index_ts["src/index.ts"]
  package__ankhorage_zora_chessboard --> entrypoint_src_index_ts
  module_src_index_ts["src/index.ts"]
